steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartpaydoc', '.']
  
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smartpaydoc']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'smartpaydoc'
      - '--image'
      - 'gcr.io/$PROJECT_ID/smartpaydoc'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY}'

# Store the Docker image in Google Container Registry
images: ['gcr.io/$PROJECT_ID/smartpaydoc']

# Timeout after 15 minutes
timeout: 900s

# Substitution variables that need to be set in Cloud Build triggers
substitutions:
  _ANTHROPIC_API_KEY: ''  # This will be set in the Cloud Build trigger
