[build]
  command = "pip install -r requirements.txt && python -m pip install --upgrade pip"
  publish = "web/static"
  functions = "netlify/functions"
  
[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
