services:
  - type: web
    name: smartpaydoc
    env: docker
    plan: free
    region: oregon
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: chmod +x ./start.sh && ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/app"
      - key: PORT
        value: "10000"
      - key: CACHE_EMBEDDINGS
        value: "true"
      - key: CACHE_DIRECTORY
        value: "/app/cache"
      - key: PYTHON_VERSION
        value: "3.9"
    envFromFile:
      - .env
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    numInstances: 1
