services:
  - type: web
    name: smartpaydoc
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install fastapi uvicorn python-multipart
    startCommand: uvicorn web_app:app --host 0.0.0.0 --port $PORT --proxy-headers
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: PORT
        value: 10000
      - key: CACHE_EMBEDDINGS
        value: "true"
      - key: CACHE_DIRECTORY
        value: "/opt/render/project/cache"
    envFromFile:
      - .env
    healthCheckPath: /health
    autoDeploy: true
