services:
  - type: web
    name: smartpaydoc
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn web_app:app --host 0.0.0.0 --port $PORT --proxy-headers
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: CACHE_EMBEDDINGS
        value: "true"
      - key: CACHE_DIRECTORY
        value: "./cache"
    envFromFile:
      - .env
    healthCheckPath: /health
    autoDeploy: true
